name: cifiasm
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - snakemake
  - samtools
  - hifiasm
  - gfatools
  - yahs
  - k8
  - nextflow
  - python
  - biopython
  - numpy
  - matplotlib